// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZcXZKo_5RjIhe5XSHaDWqIkYnARc5-w',
    appId: '1:563591011785:web:805a2462d2983b32e35c18',
    messagingSenderId: '563591011785',
    projectId: 'fir-cst9',
    authDomain: 'fir-cst9.firebaseapp.com',
    storageBucket: 'fir-cst9.appspot.com',
    measurementId: 'G-6RL98LWVLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5a6Qg0mJrBUDoNgtBvqofMcM7XgqJwvA',
    appId: '1:563591011785:android:12880b3bf56611e4e35c18',
    messagingSenderId: '563591011785',
    projectId: 'fir-cst9',
    storageBucket: 'fir-cst9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFF3iFCeRZH7JR12KtsFZ6Oc8A4wrQUE',
    appId: '1:563591011785:ios:7f8ea336d5be6d81e35c18',
    messagingSenderId: '563591011785',
    projectId: 'fir-cst9',
    storageBucket: 'fir-cst9.appspot.com',
    iosClientId: '563591011785-3rvacdm9fantdr60lta5a9n09vrg1aet.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCst9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFF3iFCeRZH7JR12KtsFZ6Oc8A4wrQUE',
    appId: '1:563591011785:ios:7f8ea336d5be6d81e35c18',
    messagingSenderId: '563591011785',
    projectId: 'fir-cst9',
    storageBucket: 'fir-cst9.appspot.com',
    iosClientId: '563591011785-3rvacdm9fantdr60lta5a9n09vrg1aet.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCst9',
  );
}
